graph TD
    subgraph Core ["APIサーバー"]
        direction LR
        Supabase["Supabase"]
        FastAPI["FastAPI"]
        Gemini["Gemini"]
        Frontend["HTML / CSS / D3.js"]
        X["X (SNS)"]
        
        Frontend <-->|fastAPIのライブラリを使用| FastAPI
    end

    Render["Render / 公開サーバー"]
    client["神戸市/Chrome最新バージョン"]

    X <-->|投稿データを取得| FastAPI
    FastAPI <-->|データ保存・取得| Supabase
    FastAPI <-->|AI解析リクエスト| Gemini
    FastAPI -->|ホスティング| Render
    Render-->client