-- 既存のテーブルをクリア
DROP TABLE IF EXISTS quiz_responses CASCADE;
DROP TABLE IF EXISTS quiz_questions CASCADE;
DROP TABLE IF EXISTS issue_post_relations CASCADE;
DROP TABLE IF EXISTS ai_analysis_results CASCADE;
DROP TABLE IF EXISTS issue_catalog CASCADE;
DROP TABLE IF EXISTS sns_posts CASCADE;
DROP TABLE IF EXISTS chat_histories CASCADE;

-- 1. 検索・チャット履歴テーブル（Gemini風のID別URL管理用）
CREATE TABLE chat_histories (
    id text PRIMARY KEY,            -- 例: '3d5f6b439058698f'
    query text not null,            -- 検索クエリやタイトル
    results jsonb,                  -- What/Why/Howのツリー構造や分析結果をJSONで格納
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create sns_posts table
CREATE TABLE sns_posts (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    platform varchar DEFAULT 'X',
    original_post_id varchar UNIQUE NOT NULL,
    post_text text NOT NULL,
    author_username varchar,
    likes_count int8 DEFAULT 0,
    replies_count int8 DEFAULT 0,
    posted_at timestamp with time zone,
    collected_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- 3. Create issue_catalog table (履歴IDとの紐づけもオプションで持たせると便利です)
CREATE TABLE issue_catalog (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    history_id text REFERENCES chat_histories(id) ON DELETE CASCADE, -- どの検索セッションから生まれたか
    main_category varchar,      -- カテゴリ_大きい
    sub_category varchar,       -- カテゴリー_中
    detail_category varchar,    -- カテゴリ_小さい
    ai_summary text,
    total_priority_score int4,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create ai_analysis_results table
CREATE TABLE ai_analysis_results (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sns_post_id int8 REFERENCES sns_posts(id) ON DELETE CASCADE,
    is_valid_issue boolean,
    sentiment_score float8,     -- 感情_スコア
    priority_score int4,
    analyzed_at timestamp
);

-- 5. Create issue_post_relations table
CREATE TABLE issue_post_relations (
    issue_id int8 REFERENCES issue_catalog(id) ON DELETE CASCADE, -- 問題_id
    sns_post_id int8 REFERENCES sns_posts(id) ON DELETE CASCADE,
    PRIMARY KEY (issue_id, sns_post_id)
);

-- 6. Create quiz_questions table
CREATE TABLE quiz_questions (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    issue_id int8 REFERENCES issue_catalog(id) ON DELETE CASCADE, -- 問題_id
    question_text text,
    correct_answer boolean,                     -- 正しい答え
    created_at timestamp
);

-- 7. Create quiz_responses table
CREATE TABLE quiz_responses (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quiz_question_id int8 REFERENCES quiz_questions(id) ON DELETE CASCADE,
    selected_answer boolean,                    -- selected_回答
    is_correct boolean,                         -- is_正しい
    answered_at timestamp                       -- 答えた_at
);
-- Threadsのコメント・リプライを保存するテーブル
CREATE TABLE threads_comments (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    platform varchar DEFAULT 'Threads',
    post_id varchar not null,                 -- 自分のどの投稿に対するリプライか
    comment_id varchar UNIQUE not null,       -- Threads側のコメントID（重複防止）
    comment_text text,                        -- コメント本文
    author_username varchar,                  -- コメントしたユーザーのID/名前
    posted_at timestamp with time zone,     -- コメントされた日時
    collected_at timestamp with time zone default timezone('utc'::text, now()) not null
); 