[project]
name = "kobe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jun", email = "" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.4",
    "workers-py>=1.17.7",
]

[project.scripts]
kobe = "kobe:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
