DROP TABLE IF EXISTS quiz_responses CASCADE;
DROP TABLE IF EXISTS quiz_questions CASCADE;
DROP TABLE IF EXISTS issue_post_relations CASCADE;
DROP TABLE IF EXISTS ai_analysis_results CASCADE;
DROP TABLE IF EXISTS issue_catalog CASCADE;
DROP TABLE IF EXISTS sns_posts CASCADE;

-- 1. Create sns_posts table
CREATE TABLE sns_posts (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    platform varchar,
    original_post_id varchar,
    post_text text,
    likes_count int4,
    replies_count int4,
    posted_at timestamp,
    collected_at timestamp
);

-- 2. Create issue_catalog table
CREATE TABLE issue_catalog (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    main_category varchar,      -- カテゴリ_大きい
    sub_category varchar,       -- カテゴリー_中
    detail_category varchar,    -- カテゴリ_小さい
    ai_summary text,
    total_priority_score int4,
    created_at timestamp
);

-- 3. Create ai_analysis_results table
CREATE TABLE ai_analysis_results (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sns_post_id int8 REFERENCES sns_posts(id),
    is_valid_issue boolean,
    sentiment_score float8,     -- 感情_スコア
    priority_score int4,
    analyzed_at timestamp
);

-- 4. Create issue_post_relations table
CREATE TABLE issue_post_relations (
    issue_id int8 REFERENCES issue_catalog(id), -- 問題_id
    sns_post_id int8 REFERENCES sns_posts(id),
    PRIMARY KEY (issue_id, sns_post_id)
);

-- 5. Create quiz_questions table
CREATE TABLE quiz_questions (
    id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    issue_id int8 REFERENCES issue_catalog(id), -- 問題_id
    question_text text,
    correct_answer boolean,                     -- 正しい答え
    created_at timestamp
);

-- 6. Create quiz_responses table
CREATE TABLE quiz_responses (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quiz_question_id int4 REFERENCES quiz_questions(id),
    selected_answer boolean,                    -- selected_回答
    is_correct boolean,                         -- is_正しい
    answered_at timestamp                       -- 答えた_at
);