DROP TABLE IF EXISTS クイズ_応答 CASCADE;
DROP TABLE IF EXISTS クイズ_質問 CASCADE;
DROP TABLE IF EXISTS issue_post_relations CASCADE;
DROP TABLE IF EXISTS ai_分析_結果 CASCADE;
DROP TABLE IF EXISTS issue_カタログ CASCADE;
DROP TABLE IF EXISTS sns_投稿 CASCADE;
-- 1. sns_投稿 テーブルの作成
CREATE TABLE sns_投稿 (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    プラットフォーム varchar,
    オリジナル_ポスト_ID varchar,
    post_text text,
    いいね_カウント int4,
    返信_カウント int4,
    投稿日_at timestamp,
    収集された_at timestamp
);

-- 2. issue_カタログ テーブルの作成
CREATE TABLE issue_カタログ (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    カテゴリ_大きい varchar,
    カテゴリー_中 varchar,
    カテゴリ_小さい varchar,
    ai_概要 text,
    合計_優先度_スコア int4,
    作成された_at timestamp
);

-- 3. ai_分析_結果 テーブルの作成
CREATE TABLE ai_分析_結果 (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sns_post_id int8 REFERENCES sns_投稿(id),
    is_valid_issue boolean,
    感情_スコア float8,
    優先度_スコア int4,
    分析された_at timestamp
);

-- 4. issue_post_relations テーブルの作成
CREATE TABLE issue_post_relations (
    問題_id int8 REFERENCES issue_カタログ(id),
    sns_post_id int8 REFERENCES sns_投稿(id),
    PRIMARY KEY (問題_id, sns_post_id)
);

-- 5. クイズ_質問 テーブルの作成
CREATE TABLE クイズ_質問 (
    id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    問題_id int8 REFERENCES issue_カタログ(id),
    質問_テキスト text,
    正しい答え boolean,
    作成された_at timestamp
);

-- 6. クイズ_応答 テーブルの作成
CREATE TABLE クイズ_応答 (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    クイズ_質問_id int4 REFERENCES クイズ_質問(id),
    selected_回答 boolean,
    is_正しい boolean,
    答えた_at timestamp
);